WITH D AS (
    SELECT CAR_ID, DATEDIFF(END_DATE,START_DATE)+1 AS DIFF
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY    
), AVG_D AS(
    SELECT CAR_ID, ROUND(AVG(DIFF),1) AS AVERAGE_DURATION
    FROM D
    GROUP BY CAR_ID
)

SELECT *
FROM AVG_D
WHERE AVERAGE_DURATION >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC;