SELECT BOOK_ID,
       DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK
WHERE CATEGORY = '인문'
  AND PUBLISHED_DATE BETWEEN '2021-01-01' AND '2021-12-31'
ORDER BY PUBLISHED_DATE;

# -- 아래보다 위에가 더 좋은 풀이
# SELECT BOOK_ID,	DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
# FROM BOOK
# WHERE CATEGORY = '인문' AND YEAR(PUBLISHED_DATE) = 2021
# ORDER BY PUBLISHED_DATE;